version: "3"
services:
    frontend:
        container_name: app
        image: calculator-app
        ports:
            - "3000:3000"
    backend:
        container_name: api
        image: calculator-api
        ports:
            - "4000:4000"